version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "ComplexP@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  app:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sqlserver;Database=testlista;User Id=sa;Password=ComplexP@ssw0rd!;"
    depends_on:
      - sqlserver
    ports:
      - "8080:80"
